[gcp_service_account]
type = "service_account"
project_id = "total-apparatus-460306-v7"
private_key_id = "b955e98de63b73a65a17191cee6c5b028dec8680"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDiFgMZNrHC5t7m
zGG+gqyaPMjCtJA0yZ4ywolGh3z8lhWILsbQIsN66wmJ3cCzY1Yi8bEA77tqizTq
OEQHjArq+lIVdMKd8DB9fv1nZjIJO3ftU77i0ib/9nPJQXGfUA8e9hZEBMWuhg4u
mhcPhydVR6fTXgjOraiJKbTXDM6+uAmUsHlIEyp3faWBaTqT8sdPRNtthPkowyxa
A2TfDKAV3wbrvw90sRZ0njVwhrummUFYhkmnQIWwAzT9V0RrLduIRbN+8jdV1vFR
JTZYf3WkS6e4f3ge2+2y6Q3MXrUx9LKMn0qAE8NRIubEFW+VA995tJd8QH8zex/X
vhe/o/h5AgMBAAECggEAB/myj4jDRc624YGnd4zcyZ6YDu1HcoNDwELmTI2CQldJ
iGmtBAHb7zm8FwfScMmR6+7meXPbgsdJHTORq8n8BxzAOUdKh7+FuGGazxNW88Ys
JXw5LT9wVoJzRG/Zch8k/2i7MZhRAGZ0eN6g7mBsSej6kb1dFmxgGAGXgmgOYYIj
wf4Bee8XzcfMXNh1nbDnWsRlTc6e52yANBX7+vjvxm4RxXwRkOlNNyQdEMbMcc8Y
wispWr9REE9f/boRMeE7Z/Mz5Gc7mqVYGslrEdL6kccUWGb/0kDnFSqJGrmy2K+g
NBkJap6B/8V86VEX4p8K6J6EN1t/4evXOR6PCwBNEQKBgQD4UFJF/Rj3GdGMwu+d
utpAOPR4evOU9zjNsAIAF9ZeJU7c/LLdHFvgzeSv448FTfo9G4LGX3PqL3xIIbEm
0viLENZJR1gzCEZZ0IkDIRdLCCSpF/Kd8RJ76JC2S3hXZNwDr4Sk2Z87xSPLARIZ
q3v/ygXdEyxfU11nsaj76p5GCQKBgQDpFY3jWcCihx3RKsqQAA7DqqsDZ4KLLijs
wIvimljD0PBB5sKqId321Kf5sZRuCima1UCUTUaA4m9xudPURItEPPTS3JRTvUky
ZyASIsqbDukDJDp/buMAFosxiOwPqhSOgUe2sxnXF1dUCRs0K55STeZqzsM8Rfck
BUY+ABY68QKBgEP7CWsrzWfo45ubyqnt+85VSWiqkIEZ5a06IHISFJgVsq+BZx5t
oyG6fH9C12bmYDnWjEju3PciJO5CexNb8rtv0pqhM55VB52TH8+BgbUC97ZrXfqr
gxn1I5kktD+I10sTBEd1ZMiiQhhTpLbuYbY3gr9xflZiplG7K748DzSxAoGACu+y
957ndfjHAmBynq0SBEZGveMmcedZjjo+lgRN8+oiy8TLD3aFVqaFtyaI41zgtN4a
qJqzmyqEth5U/Rm2Ox5tElO9NeykuZOzIoa1YO8jKb2SbRZD2mY0Y7+b6+Q8EK+q
ML1YkgoLU+sVdq4xQIVdMVfAO1zBCtSghho08NECgYAEvU71p36bbZTi/9Pt98LV
7mOJh5djRes4TH5QTCMRmxBvt1E9KLgWCoEz3mJm8FnbBKP7pfgQWFoQebrDREO0
HYryfZRFvCNm6KfQ+4H1l51MjZucUH0CL5aIjEKsgu5GduA1NaVz+QNtnWb1HbOp
m/OEmE4L2T5MVmpONkKEOw==
-----END PRIVATE KEY-----"""
client_email = "ansible@total-apparatus-460306-v7.iam.gserviceaccount.com"
client_id = "114175109993098878587"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/ansible%40total-apparatus-460306-v7.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
